# Generated by Django 5.1.3 on 2024-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
